# Generated by Django 3.2.4 on 2021-06-16 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='tracking',
            field=models.ManyToManyField(blank=True, related_name='tracked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
