# Generated by Django 3.2.4 on 2021-06-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_registereduser_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeditems', to='mainApp.feeditem', verbose_name='Author'),
        ),
    ]
