# Generated by Django 3.2.4 on 2021-06-16 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0003_alter_feeditem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeditems', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='tracking',
            field=models.ManyToManyField(blank=True, related_name='tracked_by', to='mainApp.RegisteredUser'),
        ),
    ]
